class Party:
    UNKNOWN = 'unknown'
    SYMBOL_TO_PARTY = {
        'Aeroplane': UNKNOWN,
        'Bell': UNKNOWN,
        'Bicycle': UNKNOWN,
        'Bird': UNKNOWN,
        'Book': UNKNOWN,
        'Bus': UNKNOWN,
        'Butterfly': UNKNOWN,
        'Cart Wheel': UNKNOWN,
        'Chair': UNKNOWN,
        'Clock': UNKNOWN,
        'Cockerel': UNKNOWN,
        'Cup': UNKNOWN,
        'Elephant': 'UNP',
        'Eye': UNKNOWN,
        'Flower': UNKNOWN,
        'Hand': 'SLFP',
        'House': UNKNOWN,
        'Key': UNKNOWN,
        'Key': UNKNOWN,
        'Ladder': UNKNOWN,
        'Lamp': UNKNOWN,
        'Mortar': UNKNOWN,
        'Omnibus': UNKNOWN,
        'Orange': UNKNOWN,
        'Pair Of Scales': UNKNOWN,
        'Pair Of Spectacles': UNKNOWN,
        'Pineapple': UNKNOWN,
        'Pot': UNKNOWN,
        'Rabbit': UNKNOWN,
        'Radio': UNKNOWN,
        'Saw': UNKNOWN,
        'Sewing Machine': UNKNOWN,
        'Ship': UNKNOWN,
        'Spoon': UNKNOWN,
        'Star': UNKNOWN,
        'Sun': UNKNOWN,
        'Table': UNKNOWN,
        'Tree': UNKNOWN,
        'Tumbler': UNKNOWN,
        'Umbrella': UNKNOWN,
        'Uncontested': UNKNOWN,
        'Wheel': UNKNOWN,
        'Window': UNKNOWN,
    }
