class Party:
    UNKNOWN = '?'
    INDEPENDENT = 'Independent'
    SYMBOL_TO_PARTY = {
        'Aeroplane': UNKNOWN,
        'Bell': UNKNOWN,
        'Bicycle': 'LP/ACTC',
        'Bird': INDEPENDENT,
        'Book': UNKNOWN,
        'Bus': UNKNOWN,
        'Butterfly': INDEPENDENT,
        'Cart Wheel': 'CIC',
        'Chair': 'LSSP',
        'Clock': UNKNOWN,
        'Cockerel': 'CWC',
        'Cup': UNKNOWN,
        'Elephant': 'UNP',
        'Eye': INDEPENDENT,
        'Flower': UNKNOWN,
        'Hand': 'SLFP',
        'House': 'ITAK',
        'Key': 'LSSP',
        'Ladder': UNKNOWN,
        'Lamp': 'BSP',
        'Mortar': UNKNOWN,
        'Omnibus': UNKNOWN,
        'Orange': UNKNOWN,
        'Pair Of Scales': 'UNP',
        'Pair Of Spectacles': 'CIC',
        'Pineapple': 'CP',
        'Pot': UNKNOWN,
        'Rabbit': UNKNOWN,
        'Radio': UNKNOWN,
        'Saw': UNKNOWN,
        'Sewing Machine': UNKNOWN,
        'Ship': UNKNOWN,
        'Spoon': UNKNOWN,
        'Star': 'CP',
        'Sun': UNKNOWN,
        'Table': UNKNOWN,
        'Tree': INDEPENDENT,
        'Tumbler': UNKNOWN,
        'Umbrella': 'UNP',
        'Uncontested': UNKNOWN,
        'Wheel': UNKNOWN,
        'Window': UNKNOWN,
    }

    PARTY_TO_EMOJI = {
        'UNP': '🟢',
        'SLFP': '🔵',
        'CIC': '🟠',
        'LSSP': '🔴',
        'BSP': '🔴',
        'CP': '🔴',
        'LP': '🔴',
        INDEPENDENT: '⚪',
        UNKNOWN: '',
    }
